CREATE TABLE IF NOT EXISTS DOLLAR (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATE DATE,
    VALUE NUMERIC(10, 2)
);

INSERT INTO DOLLAR (DATE, VALUE) VALUES (current_date, 30.12);
INSERT INTO DOLLAR (DATE, VALUE) VALUES (current_date - 1, 29.26);
INSERT INTO DOLLAR (DATE, VALUE) VALUES (current_date - 2, 28.47);
INSERT INTO DOLLAR (DATE, VALUE) VALUES (current_date - 3, 28.02);